/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.nlt.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.nlt.include.Config;
import org.nlt.model.Users;
import org.nlt.services.UserServices;

/**
 *
 * @author Giridhar
 */
public class StudentFrame extends javax.swing.JInternalFrame {
    private Users user;

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentnameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        phonenoField = new javax.swing.JTextField();
        approvedButton = new javax.swing.JButton();
        notApprovedButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentDetailTable = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("STUDENT NAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("EMAIL");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("PHONE NO.");

        approvedButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        approvedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/nlt/view/check.jpg"))); // NOI18N
        approvedButton.setText("APPROVED");
        approvedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approvedButtonActionPerformed(evt);
            }
        });

        notApprovedButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        notApprovedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/nlt/view/delete.png"))); // NOI18N
        notApprovedButton.setText("NOT APPROVED");
        notApprovedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notApprovedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(approvedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(studentnameField, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(emailField)
                            .addComponent(phonenoField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(notApprovedButton)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phonenoField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(approvedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notApprovedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        studentDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        studentDetailTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentDetailTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentDetailTable);

        jPanel2.add(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approvedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approvedButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            user.setStatus(3);
            UserServices.UpdateUser(user);
            JOptionPane.showMessageDialog(this, "User approved successfully", "Student frame", JOptionPane.INFORMATION_MESSAGE);
            Config.mainframe.setUserMap();//will refresh map variable
            Config.studentframe.setTable();//will refresh table 
            approvedButton.setEnabled(false);
            notApprovedButton.setEnabled(false);

        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(this, ex, "Student frame", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_approvedButtonActionPerformed

    private void studentDetailTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentDetailTableMouseClicked
        // TODO add your handling code here:
        try
        {
            String email = studentDetailTable.getValueAt(studentDetailTable.getSelectedRow(), 2).toString();
            user = Config.userMap.get(email);
            studentnameField.setText(user.getName());
            emailField.setText(user.getEmail());
            phonenoField.setText(user.getPhone());
            
            if(user.getStatus()==3)
            {
                notApprovedButton.setEnabled(true);
                approvedButton.setEnabled(false);
            }
            else if(user.getStatus()==1)
            {
                notApprovedButton.setEnabled(false);
                approvedButton.setEnabled(true);
            }
        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(this, ex, "Student frame", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_studentDetailTableMouseClicked

    private void notApprovedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notApprovedButtonActionPerformed
        // TODO add your handling code here:
         try
        {
            user.setStatus(1);
            UserServices.UpdateUser(user);
            JOptionPane.showMessageDialog(this, "User approval removed successfully", "Student frame", JOptionPane.INFORMATION_MESSAGE);
            Config.mainframe.setUserMap();//will refresh map variable
            Config.studentframe.setTable();//will refresh table 
            approvedButton.setEnabled(false);
            notApprovedButton.setEnabled(false);

        }
        catch(Exception ex)
        {
             JOptionPane.showMessageDialog(this, ex, "Student frame", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_notApprovedButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approvedButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton notApprovedButton;
    private javax.swing.JTextField phonenoField;
    private javax.swing.JTable studentDetailTable;
    private javax.swing.JTextField studentnameField;
    // End of variables declaration//GEN-END:variables
 //this method will display list of student i.e users in table
    public void setTable() {
        try {
            //only student object we are returning
            List<Users> userList = UserServices.getUserList();
            int i = 0;
            String[] cols = {"NAME", "CLASS", "EMAIL", "CONTACT", "DOB", "APPROVED"};
            String[][] data = new String[userList.size()][cols.length];
            for (Users user : userList) {
                data[i][0] = user.getName();
                data[i][1] = user.getClassName();
                data[i][2] = user.getEmail();
                data[i][3] = user.getPhone();
                data[i][4] = user.getDob().toString();
                if (user.getStatus() == 3) {
                    data[i][5] = "APPROVED";

                } else {
                    data[i][5] = "NOT APPROVED";
                }
                i++;
            }
            DefaultTableModel model = new DefaultTableModel(data, cols);
            studentDetailTable.setModel(model);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Student frame", JOptionPane.ERROR_MESSAGE);
        }
    }

}
